name: Documentation
on:
  release:
    types: [published]
  push:
    branches:
      - main
env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Build release docs
      if: github.event_name == 'release'
      run: uv run scripts/build_docs.py docs-build

    - name: Build dev docs
      if: github.event_name == 'push'
      run: uv run scripts/build_docs.py docs-build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs-build
